### ISSUE TITLE
generate.sh should be robust to incorrect YAML files.

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/templates#42]
Incorrect YAML files can lead to hard to decipher errors, or even completely strange behavior.
For instance, a `meta.yml` which contained the following incorrect part:

```yaml
dependencies:
- opam:
    name: coq-coqeal
    version: '{>= "1.0.3"}'
    name: coq-mathcomp-real-closed
    version: '{>= "1.0.4"}'
    name"coq-mathcomp-bigenough '{>= "1.0.0"}'
```
(https://github.com/math-comp/apery/blob/57704e1e97be40be9ffc3ae77b2a894200804f87/meta.yml#L58-L64)

led, when running `generate.sh` (with the mustache-go implementation) to:

```
mkdir: création du répertoire '.circleci'
Generating .circleci/config.yml...
mkdir: création du répertoire '.github'
mkdir: création du répertoire '.github/workflows'
Generating .github/workflows/coq-action.yml...
Generating Error: yaml: line 64: could not find expected ':'.opam...
Generating default.nix...
Generating Error: yaml: line 64: could not find expected ':'.opam...
Generating index.md...
Generating README.md...
Generating .travis.yml...
```

and to the creation of 4 files (`default.nix`, `index.md`, `README.md` and... `Error: yaml: line 64: could not find expected ':'.opam"`) which all contained:

```
Error: yaml: line 64: could not find expected ':'
```
