### ISSUE TITLE
Adding optional listing of former project maintainers and displaying them in README

### ISSUE THREAD

**Issue by palmskog** [coq-community/templates#51]
To give proper credit to our maintainers, I think it would be appropriate to store the coq-community maintainership history in `meta.yml`, regardless of whether it is displayed in `README.md` or not. Based on discussion in the Zulip, there are two convenient ways to do this in `meta.yml`, either as part of the `maintainers` list or as part of a new list.

First option example:
```
maintainers:
- name: Karl Palmskog
  nickname: palmskog
  current: true
- name: Hugo Herbelin
  nickname: herbelin
```

Second option example:
```
maintainers:
- name: Karl Palmskog
  nickname: palmskog

former_maintainers:
- name: Hugo Herbelin
  nickname: herbelin
```

Note that `former_maintainers` does not necessarily need to contain the nicknames.
